# Generated by Django 5.1 on 2024-09-13 18:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('no_carnet', models.CharField(max_length=10, unique=True)),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Física'), ('juridica', 'Jurídica')], max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais_origen', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('idioma_nativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('signatura_topografica', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('ano_publicacion', models.PositiveIntegerField()),
                ('ciencia', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(to='biblioteca.autor')),
                ('editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editora')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.idioma')),
                ('tipo_bibliografia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.tipobibliografia')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=11, unique=True)),
                ('no_carnet', models.CharField(max_length=10, unique=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], default='', max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='biblioteca_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='biblioteca_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('monto_por_dia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.empleado')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.libro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.user')),
            ],
        ),
    ]
