# Generated by Django 5.1 on 2024-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="titulo",
            field=models.CharField(default="", max_length=255),
        ),
    ]
