# Generated by Django 5.1 on 2024-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0002_libro_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="descripcion",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
