# Generated by Django 5.1 on 2024-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0003_alter_libro_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
