# Generated by Django 5.1 on 2024-10-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0007_remove_libro_ciencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="ciencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biblioteca.ciencia",
            ),
        ),
    ]
